version: '3.4'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "StrongPassword???"
       MSSQL_PID: Express
    ports:
       - 1433

  cathotel_monolith:
    image: ${DOCKER_REGISTRY-}cathotelmonolith
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080

  proxy:
    image: dockercloud/haproxy
    ports: 
      - "80:80"
    links: 
      - cathotel_monolith
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock